### ISSUE TITLE
Twitter handle mistake

### ISSUE THREAD

**Issue by wlandau** [chirunconf/chirunconf.github.io#2]
https://github.com/chirunconf/chirunconf.github.io/blob/6f35af819d4f517ea1b17234a5957d3865d15c46/config.toml#L108-L111

cc @emilyriederer, @angela-li

**Comment by emilyriederer** [comment]
I aspire to be as cool as @CivicAngela. Until that time, I’ll just steal her social media handles. =)

Thanks for the catch, @wlandau!

**Comment by angela-li** [comment]
Yikes, sorry about that @emilyriederer! Fixed in the most recent commit
